baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "Lucca Ecclissi"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
    #   [[menu.main]]
    #     # Unique identifier for a menu item
    #     identifier = "posts"
    # 
    #     url = "/posts/"
    #     
    #     # You can add extra information before the name (HTML format is supported), such as icons
    #     pre = ""
    # 
    #     # You can add extra information after the name (HTML format is supported), such as icons
    #     post = ""
    # 
    #     # Display name
    #     name = "Posts"
    # 
    #     # Weights are used to determine the ordering
    #     weight = 1
    # 
    #   [[menu.main]]
    #     identifier = "tags"
    #     name = "Tags"
    #     url = "/tags/"
    #     weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/luclissi"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  # URL for the avatar on homepage
  avatarURL = "/images/avatar.jpeg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "May the Force be with you."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#F88204"

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/luclissi/"},
    {name = "instagram", url = "https://www.instagram.com/luclissi/"},
    {name = "spotify", url = "https://open.spotify.com/user/22tkl33dgepq6csgkmm47gwci?si=mu-NvXAvQcG8iWvfkah5nw"},
  ]

  # Footer text
  footer = "Luclissi"